---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Throughout the quarter, I've improved my ability to manipulate and leverage data to ultimately tell a story. Beginning with data visualizations, I first struggled with making clear plots that could enrich and represent the data well to summarize trends and patterns. In Lab 2, I identified many growth areas for plotting and working with data sets, as I lacked a fundamental understanding of the data when I was began working with it. Over time, as evident in my graphs in Challenge 7 Question 5, I demonstrated my understanding of the different aspects that make a data visualization both compelling and meaningful in the insights it conveys through specific skills such as faceting, color coding, and including descriptive labels. Enriching and finding ways to summarize data is a cornerstone of data science; these experiences have strengthened my confidence in applying different tools to uncover statistical patterns across various data sets.
